const test = require("node:test");
const assert = require("node:assert/strict");
const { createEffectGraph, serializeEffectGraph, deserializeEffectGraph, hashEffectGraph } = require("../src/color/effect-graph");
const { createColorProfile, validateColorProfile } = require("../src/color/color-profile");
const { decodeMikaAtlas, resampleLut } = require("../src/color/mika-lut");
const { action4DlogMProfile, action4DlogGraph, dlogMProfile, dlogMGraph } = require("../src/color/pipeline");
const { parseCubeText } = require("../src/color/cube-lut");
const { createOfficialLutRegistry } = require("../src/color/lut-registry");
const { buildFilterGraph } = require("../src/renderers/filter-graph-builder");

test("effect graph serialization is deterministic and versioned", () => { const graph = createEffectGraph({ adjustments: [{ id: "exposure", value: 0.25 }, { id: "contrast", value: 1.1 }] }); const serialized = serializeEffectGraph(graph); assert.equal(serialized, serializeEffectGraph(JSON.parse(JSON.stringify(graph)))); assert.deepEqual(deserializeEffectGraph(serialized), graph); assert.match(serialized, /\"version\":1/); assert.equal(hashEffectGraph(graph), hashEffectGraph(deserializeEffectGraph(serialized))); });
test("color profile rejects unsupported mode and preserves unknown state", () => { const profile = createColorProfile({ cameraModel: "Action 4", colorMode: "UNKNOWN", detectionConfidence: "UNKNOWN", source: "TEST" }); assert.equal(validateColorProfile(profile).valid, true); assert.equal(profile.colorMode, "UNKNOWN"); });
test("MIKA atlas maps 2x2 tiles into a cubic LUT", () => { const data = new Uint8Array(8 * 8 * 3); for (let y = 0; y < 8; y++) for (let x = 0; x < 8; x++) { const i = (y * 8 + x) * 3; data[i] = x; data[i + 1] = y; data[i + 2] = x + y; } const atlas = decodeMikaAtlas({ width: 8, height: 8, data }, { tileSize: 4, columns: 2, rows: 2 }); assert.equal(atlas.size, 4); assert.deepEqual(atlas.values[0], [0, 0, 0]); assert.deepEqual(atlas.values[(3 * 4 + 2) * 4 + 1], [5 / 255, 6 / 255, 11 / 255]); assert.equal(resampleLut(atlas, 2).values.length, 8); });
test("official camera profiles map each Action model to its own technical transform", () => { const action4 = action4DlogGraph().colorTransform.colorProfile; assert.equal(action4.technicalTransformId, "action4.dlogm.rec709.website-cube"); assert.equal(dlogMProfile("Action5Pro").technicalTransformId, "action5pro.dlogm.rec709.website-cube"); assert.equal(dlogMProfile("Action6").technicalTransformId, "action6.dlogm.rec709.website-cube"); assert.equal(dlogMGraph("Action4", "action4.creative.forest-pro").styleStack[0].resourceId, "action4.creative.forest-pro"); });
test("CUBE parser preserves title, comments, domains, and arbitrary 3D sizes", () => { const cube = parseCubeText('# comment\nTITLE "Test Look"\nLUT_3D_SIZE 2\nDOMAIN_MIN -1 0 0\nDOMAIN_MAX 1 1 2\n0 0 0\n1 0 0\n0 1 0\n1 1 0\n0 0 1\n1 0 1\n0 1 1\n1 1 1\n', "test.cube"); assert.equal(cube.title, "Test Look"); assert.equal(cube.comments[0], "comment"); assert.deepEqual(cube.domainMin, [-1, 0, 0]); assert.deepEqual(cube.domainMax, [1, 1, 2]); assert.equal(cube.values.length, 8); });
test("APK Hald remains registered for research but cannot be loaded into V2 pipeline", async () => { const registry = createOfficialLutRegistry(require("node:path").resolve(__dirname, "..", "..")); assert.equal(registry.get("action4.dlogm.rec709.apk-hald").availability, "RESEARCH_ONLY"); await assert.rejects(() => registry.load("action4.dlogm.rec709.apk-hald"), /Research-only LUT/); });
test("official technical transform precedes the official Rec.709 creative look", async () => { const registry = createOfficialLutRegistry(require("node:path").resolve(__dirname, "..", "..")); const result = await buildFilterGraph({ graph: action4DlogGraph("action4.creative.ice-pro"), lutRegistry: registry, styleRegistry: null, cacheRoot: "unused" }); const technicalAt = result.filterGraph.indexOf("Action 4 D-Log M to Rec.709 V1.cube"); const creativeAt = result.filterGraph.indexOf("Action 4 Ice Pro.cube"); assert.ok(technicalAt >= 0); assert.ok(creativeAt > technicalAt); });
test("a technical transform cannot be substituted with the wrong camera LUT", async () => { const registry = createOfficialLutRegistry(require("node:path").resolve(__dirname, "..", "..")); const profile = { ...action4DlogMProfile(), technicalTransformId: "action5pro.dlogm.rec709.website-cube" }; const graph = createEffectGraph({ colorTransform: { kind: "technical-color", enabled: true, colorProfile: profile, intensity: 1 } }); await assert.rejects(() => buildFilterGraph({ graph, lutRegistry: registry, styleRegistry: null, cacheRoot: "unused" }), /camera family does not match/); });
