const test = require("node:test");
const assert = require("node:assert/strict");
const { ThumbScheduler } = require("../src/thumbnail/thumb-scheduler");
const { computeWindow } = require("../src/renderer/virtual-grid");

test("scheduler enforces concurrency limit", async () => { const s = new ThumbScheduler({ concurrency: 3 }); let active = 0, max = 0; const spin = new Promise(resolve => { for (let i = 0; i < 12; i++) s.enqueue(Object.assign(() => new Promise(r => setTimeout(() => { max = Math.max(max, active); active++; setTimeout(() => { active--; r({ cacheHit: false }); }, 5); }, 1)), { priority: i % 3 })); setTimeout(resolve, 400); }); await spin; assert.ok(max <= 3, "active never exceeds concurrency"); const snap = s.snapshot(); assert.equal(snap.requested, 12); assert.equal(snap.loaded, 12); });
test("scheduler prioritizes higher priority tasks among queued work", async () => { const s = new ThumbScheduler({ concurrency: 1 }); const order = []; const waiter = new Promise(resolve => { let count = 0; const done = () => { if (++count === 2) resolve(); }; s.enqueue(Object.assign(() => new Promise(r => setTimeout(() => { r({}); }, 20)), { priority: 0 })); s.enqueue(Object.assign(() => new Promise(r => { order.push("low"); r({}); done(); }), { priority: 1 })); setTimeout(() => s.enqueue(Object.assign(() => new Promise(r => { order.push("high"); r({}); done(); }), { priority: 5 })), 5); }); await waiter; assert.deepEqual(order, ["high", "low"]); });
test("scheduler can cancel low priority queued tasks", async () => { const s = new ThumbScheduler({ concurrency: 1 }); const waiter = new Promise(resolve => { const first = Object.assign(() => new Promise(r => setTimeout(() => { r({}); resolve(); }, 30)), { priority: 5 }); s.enqueue(first); s.enqueue(Object.assign(() => new Promise(() => {}), { priority: 1, token: "far" })); setTimeout(() => s.cancelBelow(3), 5); }); await waiter; assert.equal(s.snapshot().requested, 1); });
test("virtual window keeps DOM far below asset total", () => { const result = computeWindow({ scrollTop: 0, viewportHeight: 900, itemHeight: 88, gap: 0, columns: 1, total: 85, overscanRows: 2 }); assert.ok(result.end - result.start < 20, "first window is small"); assert.equal(result.end, 13, "first visible row 0..10 plus 2 overscan rows yields end=13 for a 900px viewport"); });
