const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { ensureThumbnail, ensurePoster } = require("../src/thumbnail/thumbnail-loader");

test("cache hit returns existing file without running ffmpeg", async () => { const cacheRoot = fs.mkdtempSync(path.join(os.tmpdir(), "dji-cache-")); const assetId = "a1"; const first = await ensureThumbnail({ ffmpeg: path.join(os.tmpdir(), "missing-ffmpeg"), assetId, previewPath: null, originalPath: null, cacheRoot }); assert.equal(first, null); fs.writeFileSync(path.join(cacheRoot, assetId + ".jpg"), "jpeg"); const second = await ensureThumbnail({ ffmpeg: path.join(os.tmpdir(), "missing-ffmpeg"), assetId, previewPath: null, originalPath: null, cacheRoot }); assert.equal(second, path.join(cacheRoot, assetId + ".jpg")); });
test("cache invalidation on asset id change produces separate files", async () => { const cacheRoot = fs.mkdtempSync(path.join(os.tmpdir(), "dji-cache-")); fs.writeFileSync(path.join(cacheRoot, "a1.jpg"), "a"); fs.writeFileSync(path.join(cacheRoot, "a2.jpg"), "b"); assert.equal(await ensureThumbnail({ assetId: "a1", previewPath: null, originalPath: null, cacheRoot }), path.join(cacheRoot, "a1.jpg")); assert.equal(await ensureThumbnail({ assetId: "a2", previewPath: null, originalPath: null, cacheRoot }), path.join(cacheRoot, "a2.jpg")); assert.notEqual(fs.readFileSync(path.join(cacheRoot, "a1.jpg")).toString(), fs.readFileSync(path.join(cacheRoot, "a2.jpg")).toString()); });
test("MISC source signature change invalidates cache entry", async () => { const cacheRoot = fs.mkdtempSync(path.join(os.tmpdir(), "dji-cache-")); const thm = path.join(cacheRoot, "clip.THM"); fs.writeFileSync(thm, "v1"); const first = await ensureThumbnail({ assetId: "sig1", thmPath: thm, scrPath: null, previewPath: null, originalPath: null, cacheRoot }); const later = Date.now() + 5000; fs.utimesSync(thm, later / 1000, later / 1000); fs.writeFileSync(thm, "v2"); const second = await ensureThumbnail({ assetId: "sig1", thmPath: thm, scrPath: null, previewPath: null, originalPath: null, cacheRoot }); assert.notEqual(first, second, "updated THM produces a new cache file"); assert.equal(fs.readFileSync(second).toString(), "v2"); });

test("poster cache is separate from thumbnail cache", async () => { const thumbRoot = fs.mkdtempSync(path.join(os.tmpdir(), "dji-th-")); const posterRoot = fs.mkdtempSync(path.join(os.tmpdir(), "dji-po-")); const scr = path.join(posterRoot, "clip.SCR"); fs.writeFileSync(scr, "scr"); const poster = await ensurePoster({ assetId: "p1", scrPath: scr, previewPath: null, originalPath: null, posterRoot }); assert.equal(path.dirname(poster), posterRoot); assert.ok(path.basename(poster).startsWith("p1-")); assert.equal(fs.readdirSync(thumbRoot).length, 0); });
