(() => {
  const api = window.djiMedia;
  const state = { snapshot: null, selectedId: null, colorMode: "raw", colorBusy: false, colorRequest: 0, colorTimer: null };
  const elements = {
    deviceStatus: document.getElementById("device-status"), scanButton: document.getElementById("scan-button"), fileCount: document.getElementById("file-count"), storageList: document.getElementById("storage-list"), libraryTitle: document.getElementById("library-title"), summary: document.getElementById("summary"), grid: document.getElementById("media-grid"), empty: document.getElementById("empty-state"), error: document.getElementById("error-banner"), video: document.getElementById("preview-video"), colorPreview: document.getElementById("color-preview"), videoEmpty: document.getElementById("video-empty"), play: document.getElementById("play-button"), seek: document.getElementById("seek-bar"), current: document.getElementById("current-time"), total: document.getElementById("total-time"), title: document.getElementById("preview-title"), badge: document.getElementById("source-badge"), facts: document.getElementById("preview-facts"), export: document.getElementById("export-button")
  };
  const unknown = value => value === "UNKNOWN" || value === null || value === undefined;
  const formatNumber = value => unknown(value) ? "UNKNOWN" : Number(value).toLocaleString();
  const formatDuration = value => { if (unknown(value)) return "UNKNOWN"; const ms = Math.max(0, Math.round(Number(value) * 1000)); const minutes = Math.floor(ms / 60000).toString().padStart(2, "0"); const seconds = Math.floor(ms / 1000 % 60).toString().padStart(2, "0"); const millis = (ms % 1000).toString().padStart(3, "0"); return minutes + ":" + seconds + "." + millis; };
  const create = (tag, className, text) => { const node = document.createElement(tag); if (className) node.className = className; if (text !== undefined) node.textContent = text; return node; };
  function setDeviceStatus(snapshot) { const device = snapshot.devices.find(item => item.status === "POSSIBLE_DJI_STORAGE"); elements.deviceStatus.replaceChildren(create("span", "status-dot " + (device ? "connected" : "offline")), create("span", device ? (device.cameraModel && device.cameraModel !== "UNKNOWN" ? device.cameraModel + " detected" : "DJI storage detected") : "No DJI camera detected")); }
  function renderStorage(snapshot) { elements.storageList.replaceChildren(); const rows = snapshot.devices.length ? snapshot.devices : [{ label: "No removable DJI volume", status: "NOT_DETECTED" }]; for (const device of rows) { const row = create("div", "storage-row"); const info = create("div", "storage-info"); info.append(create("strong", "", device.cameraModel && device.cameraModel !== "UNKNOWN" ? device.cameraModel : device.label), create("small", "", (device.label || "UNKNOWN") + " / " + device.status)); row.append(create("span", "drive-icon", "[]"), info); elements.storageList.append(row); } }
  function renderSummary(snapshot) { elements.fileCount.textContent = String(snapshot.files.length); elements.libraryTitle.textContent = snapshot.assets.length + " clip" + (snapshot.assets.length === 1 ? "" : "s"); const pairing = snapshot.pairing || { highConfidence: 0, audioCandidates: 0 }; elements.summary.replaceChildren(create("span", "", snapshot.files.filter(file => file.extension === "mp4").length + " Original"), create("span", "", pairing.highConfidence + " LRF paired"), create("span", "", pairing.audioCandidates + " AAC candidate")); }
  function renderGrid(snapshot) { elements.grid.replaceChildren(); elements.empty.hidden = snapshot.assets.length > 0; for (const asset of snapshot.assets) { const card = create("button", "media-card"); card.type = "button"; card.dataset.assetId = asset.id; card.setAttribute("aria-label", "Open " + asset.original.name); const thumb = create("div", "thumb"); if (asset.preview !== "UNKNOWN") { const video = document.createElement("video"); video.muted = true; video.preload = "metadata"; video.playsInline = true; video.src = "dji-media://asset/" + encodeURIComponent(asset.id); video.addEventListener("loadedmetadata", () => { video.currentTime = Math.min(0.1, video.duration || 0); }); thumb.append(video); } else thumb.append(create("span", "thumb-missing", "No LRF")); const body = create("div", "card-body"); const probe = asset.original.probe; const fps = probe.fps === "UNKNOWN" ? "UNKNOWN" : Number(probe.fps.value).toFixed(2) + " fps"; body.append(create("strong", "card-name", asset.original.name), create("span", "card-meta", formatDuration(probe.duration) + " / " + formatNumber(probe.width) + "x" + formatNumber(probe.height)), create("span", "card-meta", (probe.codec || "UNKNOWN").toUpperCase() + " / " + fps)); const tags = create("div", "card-tags"); tags.append(create("span", asset.preview === "UNKNOWN" ? "tag muted" : "tag", asset.preview === "UNKNOWN" ? "LRF unavailable" : "LRF ready")); if (asset.externalAudioCandidates.length) tags.append(create("span", "tag audio", "AAC candidate")); body.append(tags); card.append(thumb, body); card.addEventListener("click", () => selectAsset(asset.id)); elements.grid.append(card); } }
  function render(snapshot) { state.snapshot = snapshot; setDeviceStatus(snapshot); renderStorage(snapshot); renderSummary(snapshot); renderGrid(snapshot); if (snapshot.errors && snapshot.errors.length) { elements.error.hidden = false; elements.error.textContent = snapshot.errors.length + " file(s) could not be probed."; } else elements.error.hidden = true; document.querySelectorAll(".media-card").forEach(card => card.classList.toggle("selected", card.dataset.assetId === state.selectedId)); }
  function renderFacts(asset, status) { const probe = asset.original.probe; const evidence = asset.pairingEvidence; const geometry = asset.displayGeometry.original; elements.facts.replaceChildren(); const facts = [["Status", status], ["Camera", asset.cameraModel], ["Original", (probe.codec || "UNKNOWN").toUpperCase() + " / " + formatNumber(probe.width) + "x" + formatNumber(probe.height)], ["Pairing", evidence === "UNKNOWN" ? "UNKNOWN" : evidence.status + " / " + evidence.score + "/100"], ["Geometry", String(geometry.displayWidth) + "x" + String(geometry.displayHeight) + " / rotation " + String(geometry.rotation)]]; for (const [label, value] of facts) { const wrapper = create("div"); wrapper.append(create("dt", "", label), create("dd", "", String(value))); elements.facts.append(wrapper); } }
  function stopColorTimer() { if (state.colorTimer) clearInterval(state.colorTimer); state.colorTimer = null; }
  function startColorTimer() { stopColorTimer(); if (state.colorMode !== "raw" && !elements.video.paused) state.colorTimer = setInterval(() => renderColorFrame(), 140); }
  async function renderColorFrame() { if (state.colorMode === "raw" || state.colorBusy || !state.selectedId || !state.snapshot) return; const asset = state.snapshot.assets.find(item => item.id === state.selectedId); if (!asset || asset.preview === "UNKNOWN") return; state.colorBusy = true; const requestId = ++state.colorRequest; try { const result = await api.renderPreviewFrame({ assetId: state.selectedId, preset: state.colorMode, timestampSeconds: elements.video.currentTime || 0 }); if (requestId === state.colorRequest) elements.colorPreview.src = result.dataUrl; } catch (error) { elements.error.hidden = false; elements.error.textContent = "Color preview: " + error.message; } finally { state.colorBusy = false; } }
  function setColorMode(mode) { state.colorMode = mode; document.querySelectorAll("[data-color-mode]").forEach(button => button.classList.toggle("active", button.dataset.colorMode === mode)); const colored = mode !== "raw"; elements.video.hidden = mode !== "raw"; elements.colorPreview.hidden = mode === "raw"; if (!elements.video.src) { elements.video.hidden = true; elements.colorPreview.hidden = true; } if (colored) renderColorFrame(); startColorTimer(); }
  async function selectAsset(assetId) { if (!state.snapshot) return; const asset = state.snapshot.assets.find(item => item.id === assetId); if (!asset) return; state.selectedId = assetId; state.colorRequest++; state.colorMode = "raw"; document.querySelectorAll("[data-color-mode]").forEach(button => button.classList.toggle("active", button.dataset.colorMode === "raw")); stopColorTimer(); document.querySelectorAll(".media-card").forEach(card => card.classList.toggle("selected", card.dataset.assetId === assetId)); elements.title.textContent = asset.original.name; elements.badge.textContent = asset.preview === "UNKNOWN" ? "UNAVAILABLE" : "LRF"; elements.export.disabled = false; const url = await api.getPreviewUrl(assetId); elements.video.pause(); elements.video.removeAttribute("src"); elements.video.load(); elements.colorPreview.hidden = true; if (!url) { elements.video.hidden = true; elements.videoEmpty.hidden = false; elements.play.disabled = true; elements.seek.disabled = true; elements.export.disabled = true; renderFacts(asset, "PREVIEW_UNAVAILABLE"); return; } elements.video.src = url; elements.video.hidden = false; elements.videoEmpty.hidden = true; elements.play.disabled = false; elements.seek.disabled = false; elements.video.load(); renderFacts(asset, "COLOR_UNKNOWN - select Action 4 D-Log M only for confirmed D-Log M footage"); }
  function setScanning() { elements.deviceStatus.replaceChildren(create("span", "status-dot pending"), create("span", "", "Scanning volumes and media...")); elements.scanButton.disabled = true; elements.scanButton.classList.add("loading"); }
  async function runScan() { setScanning(); try { const snapshot = await api.scan(); render(snapshot); return snapshot; } catch (error) { elements.error.hidden = false; elements.error.textContent = error.message; throw error; } finally { elements.scanButton.disabled = false; elements.scanButton.classList.remove("loading"); } }
  elements.scanButton.addEventListener("click", () => { runScan().catch(() => {}); });
  elements.play.addEventListener("click", () => { if (elements.video.paused) elements.video.play(); else elements.video.pause(); });
  elements.video.addEventListener("play", () => { elements.play.textContent = "||"; startColorTimer(); }); elements.video.addEventListener("pause", () => { elements.play.textContent = ">"; stopColorTimer(); });
  elements.video.addEventListener("loadedmetadata", () => { elements.seek.max = Math.round(elements.video.duration * 1000); elements.total.textContent = formatDuration(elements.video.duration); if (state.colorMode !== "raw") renderColorFrame(); });
  elements.video.addEventListener("timeupdate", () => { elements.seek.value = Math.round(elements.video.currentTime * 1000); elements.current.textContent = formatDuration(elements.video.currentTime); if (state.colorMode !== "raw") renderColorFrame(); });
  elements.seek.addEventListener("input", () => { elements.video.currentTime = Number(elements.seek.value) / 1000; if (state.colorMode !== "raw") renderColorFrame(); });
  document.querySelectorAll("[data-color-mode]").forEach(button => button.addEventListener("click", () => setColorMode(button.dataset.colorMode)));
  elements.export.addEventListener("click", async () => { const asset = state.snapshot && state.snapshot.assets.find(item => item.id === state.selectedId); if (!asset || state.colorMode === "raw") return; elements.export.disabled = true; elements.error.hidden = true; try { const result = await api.exportColor({ assetId: state.selectedId, preset: state.colorMode }); elements.error.hidden = false; elements.error.textContent = "Exported: " + result.outputPath; } catch (error) { elements.error.hidden = false; elements.error.textContent = "Export failed: " + error.message; } finally { elements.export.disabled = false; } });
  api.onSnapshot(snapshot => { const selected = state.selectedId; render(snapshot); if (selected && snapshot.assets.some(asset => asset.id === selected)) selectAsset(selected); });
  runScan().catch(() => {});
})();
