const SORT_DIRS = { latest: -1, oldest: 1, "duration-desc": -1, "duration-asc": 1, "resolution-desc": -1, "resolution-asc": 1, "fps-desc": -1, "fps-asc": 1, "size-desc": -1, "size-asc": 1, "name-asc": 1, "name-desc": -1 };
const SORT_KEYS = { latest: "created", oldest: "created", "duration-desc": "duration", "duration-asc": "duration", "resolution-desc": "resolution", "resolution-asc": "resolution", "fps-desc": "fps", "fps-asc": "fps", "size-desc": "size", "size-asc": "size", "name-asc": "name", "name-desc": "name" };
function numericOr(value, fallback) { const n = Number(value); return Number.isFinite(n) ? n : fallback; }
function parseNameTime(name) { const m = /DJI_(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name || ""); return m ? Date.UTC(m[1], m[2] - 1, m[3], m[4], m[5], m[6]) : NaN; }
function createdMs(asset) { const probe = asset.original && asset.original.probe || {}; const t = probe.creationTime && probe.creationTime !== "UNKNOWN" ? Date.parse(probe.creationTime) : NaN; if (Number.isFinite(t)) return t; const byName = parseNameTime(asset.original && asset.original.name); if (Number.isFinite(byName)) return byName; return Date.parse(asset.original && asset.original.lastWriteTime || "") || 0; }
function valueFor(asset, key) { const original = asset.original || {}; const probe = original.probe || {}; if (key === "created") return createdMs(asset); if (key === "duration") return numericOr(probe.duration, -1); if (key === "resolution") return numericOr(probe.width, 0) * Math.max(1, numericOr(probe.height, 0)); if (key === "fps") return probe.fps && probe.fps !== "UNKNOWN" ? numericOr(probe.fps.value, -1) : -1; if (key === "size") return numericOr(original.size, -1); return String(original.name || "");
}
function compareAsset(a, b, sortKey) { const key = SORT_KEYS[sortKey] || "created"; const dir = SORT_DIRS[sortKey] !== undefined ? SORT_DIRS[sortKey] : -1; const av = valueFor(a, key); const bv = valueFor(b, key); const cmp = typeof av === "string" && typeof bv === "string" ? av.localeCompare(bv, "en", { numeric: true, sensitivity: "base" }) : (av < bv ? -1 : av > bv ? 1 : 0); return cmp * dir; }
function sortAssets(assets, sortKey) { return [...assets].sort((a, b) => compareAsset(a, b, sortKey)); }
if (typeof module !== "undefined" && module.exports) { module.exports = { sortAssets, compareAsset, createdMs, SORT_DIRS, SORT_KEYS }; } else if (typeof window !== "undefined") { window.__sort = { sortAssets, compareAsset, createdMs, SORT_DIRS, SORT_KEYS }; }
